# Generated by Django 5.0.6 on 2024-07-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_in_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="number_views",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
